feat: add di/do array interface and processing
tier4/dio_ros_driver pull request #5
Opened 2024-11-18 08:49 UTC by kodamays

## Description

- din/doutの複数ポートを同期してパラレル制御できるようにするためにdio_ros_driverに複数din/dout用のIFを追加します。

## Related links

- [AEAP-989](https://tier4.atlassian.net/browse/AEAP-989)
- [dio_ros_driver改造設計書](https://eva.app.box.com/file/1691765455109)
- [電光掲示板機能確認テスト](https://eva.app.box.com/file/1701005317325)

### 修正内容

- 複数ポートの同期設定用のdin/dout用IF(/dio/din_array, /dio/dout_array)が追加され、DIOで3以上の状態切り替えが可能になります。
    - 修正内容の概要
![dio_ros_driver構成変更内容](https://github.com/user-attachments/assets/0fc27dcc-2773-465e-85b5-4cf150386b33)

    - 修正後のIF
![dio_ros_driver_IF](https://github.com/user-attachments/assets/94c19359-a4c2-4dcf-8afb-755c5225ca1d)

## Tests performed

### 修正後の結合テスト

- 既存のIF（/dio/din[0-7], /dio/dout[0-7])はeveの生産用のDIO確認ツールで今回の修正後のコードでも車両で使用するものは全て正常に動作することを確認済みです。

- 追加したIFのうち/dio/dout_arrayは車両に電光掲示板を接続した状態で実車評価を実施し、電光掲示板で想定した8状態の表示が想定通り表示されることを確認済みです。
    - [電光掲示板機能確認テスト](https://eva.app.box.com/file/1701005317325)

- 追加したIFの/dio/din_arrayはDIN0〜DIN7の値を常にトピックとして流し続けるため、DIN0〜DIN7の全ての値が出力されること、DIN０に発車ボタン、DIN1の専有ボタンの押下で/dio/din_arrayのDIN0とDIN1の値が変化することを確認済みです。

  - [dio_din_array_topic_echo.log](https://github.com/user-attachments/files/17797258/dio_din_array_topic_echo.log)

## Notes for reviewers

## Pre-review checklist for the PR author

The PR author **must** check the checkboxes below when creating the PR.

- [x] I've confirmed the [contribution guidelines].
- [x] The PR follows the [pull request guidelines].

## In-review checklist for the PR reviewers

The PR reviewers **must** check the checkboxes below before approval.

- [ ] The PR follows the [pull request guidelines].
- [ ] The PR has been properly tested.
- [ ] The PR has been reviewed by the code owners.

## Post-review checklist for the PR author

The PR author **must** check the checkboxes below before merging.

- [ ] There are no open discussions or they are tracked via tickets.
- [ ] The PR is ready for merge.

After all checkboxes are checked, anyone who has write access can merge the PR.

[contribution guidelines]: https://autowarefoundation.github.io/autoware-documentation/main/contributing/
[pull request guidelines]: https://autowarefoundation.github.io/autoware-documentation/main/contributing/pull-request-guidelines/

2024-11-18 09:02 UTC, yn-mrse commented on include/dio_ros_driver/dio_ros_driver.hpp
> +  void receiveArrayWriteReqest(const dio_ros_driver::msg::DIOArray::ConstSharedPtr &dout_array_topic); // !<@brief receive user write array request.
```suggestion
  void receiveArrayWriteRequest(const dio_ros_driver::msg::DIOArray::ConstSharedPtr &dout_array_topic); // !<@brief receive user write array request.
```

2024-11-18 09:02 UTC, yn-mrse commented on msg/DIOArray.msg
> +DIOPortValue[] values
改行コードを修正ください

2024-11-18 09:02 UTC, yn-mrse commented on msg/DIOPortValue.msg
> +bool value
改行コードを修正ください

2024-11-18 09:02 UTC, yn-mrse commented on src/dio_ros_driver.cpp
> +void DIO_ROSDriver::receiveArrayWriteReqest(const dio_ros_driver::msg::DIOArray::ConstSharedPtr &dout_array_topic) {
```suggestion
void DIO_ROSDriver::receiveArrayWriteRequest(const dio_ros_driver::msg::DIOArray::ConstSharedPtr &dout_array_topic) {
```

2024-11-18 09:03 UTC, yn-mrse commented on src/dio_ros_driver.cpp
> +                                                                                        std::bind(&DIO_ROSDriver::receiveArrayWriteReqest, this, std::placeholders::_1));
```suggestion
                                                                                        std::bind(&DIO_ROSDriver::receiveArrayWriteRequest, this, std::placeholders::_1));
```

2024-11-18 09:30 UTC, kodamays commented on include/dio_ros_driver/dio_ros_driver.hpp
> +  void receiveArrayWriteReqest(const dio_ros_driver::msg::DIOArray::ConstSharedPtr &dout_array_topic); // !<@brief receive user write array request.
@yn-mrse 
typoを修正しました。

2024-11-18 09:30 UTC, kodamays commented on src/dio_ros_driver.cpp
> +void DIO_ROSDriver::receiveArrayWriteReqest(const dio_ros_driver::msg::DIOArray::ConstSharedPtr &dout_array_topic) {
@yn-mrse 
typoを修正しました。

2024-11-18 09:30 UTC, kodamays commented on src/dio_ros_driver.cpp
> +                                                                                        std::bind(&DIO_ROSDriver::receiveArrayWriteReqest, this, std::placeholders::_1));
@yn-mrse 
typoを修正しました。

2024-11-18 09:31 UTC, kodamays commented on msg/DIOArray.msg
> +DIOPortValue[] values
@yn-mrse 
改行コードを最後に追加しました。

2024-11-18 09:32 UTC, kodamays commented on msg/DIOPortValue.msg
> +bool value
@yn-mrse 
改行コードを最後に追加しました。

2024-11-19 05:01 UTC, yn-mrse commented on src/dio_ros_driver.cpp
> +}
内部処理をreadDINPorts関数内部へ取り込む検討をお願いします。

2024-11-19 05:05 UTC, yn-mrse requested changes

2024-11-19 05:05 UTC, yn-mrse commented on src/dio_ros_driver.cpp
> +      targeted_dout_update.value_ = dout_port_data.value;
receiveWriteRequest関数の内部処理と一致すると思いますので、こちらはreceiveWriteRequestを内部的に呼び出すように変更いただけますでしょうか？

2024-11-19 08:49 UTC, kodamays commented on src/dio_ros_driver.cpp
> +}
以下のコミットでreadDINPorts関数内部へpublishDINPortValueで実施していた処理を移動し、publishDINPortValueを削除しました。
[b455b1f](https://github.com/tier4/dio_ros_driver/pull/5/commits/b455b1fd80adc0ed82d83c12fa931845114ac82d)

2024-11-19 08:54 UTC, kodamays commented on src/dio_ros_driver.cpp
> +      targeted_dout_update.value_ = dout_port_data.value;
以下のコミットでreceiveArrayWriteRequestの内部処理でreceiveWriteRequestを呼び出すように修正しました。
[b455b1f](https://github.com/tier4/dio_ros_driver/pull/5/commits/b455b1fd80adc0ed82d83c12fa931845114ac82d)

2024-11-19 09:44 UTC, s-azumi approved these changes
LGTM

2024-11-22 07:01 UTC, peeeechi commented
LGTM

2024-11-22 07:01 UTC, peeeechi approved these changes
LGTM

2024-11-22 09:07 UTC, yn-mrse approved these changes

2024-11-22 09:07 UTC, merged